import {NextResponse} from "next/server";import {supabaseServer} from "@/lib/supabase-server";import {capacityMinutes,mission,priority} from "@/lib/planning";
function local(){const d=new Date(),p=Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",weekday:"short",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d).map(x=>[x.type,x.value]));const date=`${p.year}-${p.month}-${p.day}`;const n=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(p.weekday);const type=n>=1&&n<=3?"maintenance":n===4?"execution":n===5?"sales":n===6?"life":"review";return{date,type}}
function score(tasks:any[],health:any,tx:any[],leads:any[],learning:any[],type:string){const completed=tasks.filter(t=>t.status==="done");const high=tasks.filter(t=>Number(t.importance)>=4);const execution=high.length?Math.min(40,Math.round(completed.filter(t=>Number(t.importance)>=4).length/high.length*40)):Math.min(40,completed.length*8);const healthScore=health?Math.min(20,10+(Number(health.energy||0)>=7?5:0)+(Number(health.sleep_hours||0)>=7?5:0)):0;const business=type==="sales"?Math.min(20,leads.length?10+(tx.length?10:0):0):Math.min(20,tx.length?10:10);const learn=learning.length?10:0;const life=(type==="life"||type==="review")?10:5;return{score:Math.min(100,execution+healthScore+business+learn+life),breakdown:{execution:execution+"/40",health:healthScore+"/20",business:business+"/20",learning:learn+"/10",life:life+"/10"}}}
export async function GET(){const {date,type}=local(),s=await supabaseServer(),{data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({date,type,authenticated:false,capacityMinutes:capacityMinutes(type),mission:mission(type)});
const todayStart=new Date(date+"T00:00:00+01:00").toISOString();const plan={user_id:user.id,plan_date:date,day_type:type,mission:mission(type),capacity_minutes:capacityMinutes(type),generated_at:new Date().toISOString()};const {data:planRow,error}=await s.from("daily_plans").upsert(plan,{onConflict:"user_id,plan_date"}).select().single();
const {data:open}=await s.from("tasks").select("*").eq("user_id",user.id).eq("status","todo");const tasks=open||[];const overdue=tasks.filter(t=>t.due_at&&new Date(t.due_at)<new Date(date+"T00:00:00Z"));for(const t of overdue){const next=(t.carry_count||0)+1;if(next>=3)await s.from("tasks").update({status:"decision_required",carry_count:next}).eq("id",t.id).eq("user_id",user.id);else await s.from("tasks").update({carry_count:next,due_at:null}).eq("id",t.id).eq("user_id",user.id)}
const refreshed=(await s.from("tasks").select("*").eq("user_id",user.id).eq("status","todo")).data||[];const ranked=refreshed.map(t=>({...t,_priority:priority({id:t.id,title:t.title,category:t.category,status:t.status,priority:0,due:t.due_at,estimatedMinutes:t.estimated_minutes,revenueImpact:Number(t.revenue_impact||0),strategicImpact:Number(t.strategic_impact||0),urgent:Number(t.urgency||0)>=4})})).sort((a,b)=>b._priority-a._priority);
let used=0;const buckets={must:[] as any[],should:[] as any[],optional:[] as any[]};for(const t of ranked){if(used+t.estimated_minutes<=Number(plan.capacity_minutes)){const b=buckets.must.length<3?"must":buckets.should.length<3?"should":"optional";buckets[b].push(t);used+=t.estimated_minutes}}
await s.from("daily_plan_tasks").delete().eq("plan_id",planRow.id);const links=[...buckets.must.map((t,i)=>({plan_id:planRow.id,task_id:t.id,rank:i,bucket:"must"})),...buckets.should.map((t,i)=>({plan_id:planRow.id,task_id:t.id,rank:i,bucket:"should"})),...buckets.optional.map((t,i)=>({plan_id:planRow.id,task_id:t.id,rank:i,bucket:"optional"}))];if(links.length)await s.from("daily_plan_tasks").insert(links);
const [allTasks,health,tx,leads,learning,scoreRow]=await Promise.all([s.from("tasks").select("*").eq("user_id",user.id),s.from("health_entries").select("*").eq("user_id",user.id).eq("entry_date",date).maybeSingle(),s.from("transactions").select("*").eq("user_id",user.id).gte("occurred_on",date.slice(0,7)+"-01"),s.from("leads").select("*").eq("user_id",user.id),s.from("learning_modules").select("*").eq("user_id",user.id),s.from("daily_scores").select("*").eq("user_id",user.id).eq("score_date",date).maybeSingle()]);const scoring=score(allTasks.data||[],health.data,tx.data||[],leads.data||[],learning.data||[],type);await s.from("daily_scores").upsert({user_id:user.id,score_date:date,score:scoring.score,breakdown:scoring.breakdown},{onConflict:"user_id,score_date"});return NextResponse.json({date,type,authenticated:true,plan:planRow,score:scoring.score,breakdown:scoring.breakdown,buckets,tasks:refreshed,decisionRequired:overdue.filter(t=>(t.carry_count||0)+1>=3).map(t=>t.title),previousScore:scoreRow.data?.score||null,error})}