-- Full Founder OS domain expansion
create table if not exists projects(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,name text not null,status text not null default 'active',description text,created_at timestamptz not null default now());
create table if not exists time_blocks(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,task_id uuid references tasks(id) on delete set null,event_id uuid references events(id) on delete set null,starts_at timestamptz not null,ends_at timestamptz not null,title text not null,category text not null default 'TDO',status text not null default 'planned');
create table if not exists content_items(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,title text not null,pillar text,platform text,format text,status text not null default 'Idea',publish_at timestamptz,estimated_minutes int not null default 30,notes text,created_at timestamptz not null default now());
create table if not exists sales_activities(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,lead_id uuid references leads(id) on delete cascade,activity_type text not null,occurred_at timestamptz not null default now(),notes text,next_follow_up date);
create table if not exists health_entries(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,entry_date date not null,sleep_hours numeric,sleep_quality int,steps int,exercise_minutes int,water_litres numeric,nutrition_score int,energy int,mood int,recovery int,notes text,unique(user_id,entry_date));
create table if not exists network_contacts(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,name text not null,company text,role text,email text,phone text,linkedin text,relationship_strength int not null default 1,last_contact date,next_contact date,notes text);
create table if not exists experiences(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,title text not null,experience_date date,category text,location text,notes text,memory text,created_at timestamptz not null default now());
create table if not exists journal_entries(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,entry_date date not null,title text,body text,mood int,created_at timestamptz not null default now());
create table if not exists notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,type text not null,title text not null,body text,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists daily_scores(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,score_date date not null,score int not null check(score between 0 and 100),breakdown jsonb not null default '{}',unique(user_id,score_date));
alter table profiles add column if not exists work_start time not null default '08:00';
alter table profiles add column if not exists work_end time not null default '20:00';
alter table profiles add column if not exists tdo_days int[] not null default '{4}';
alter table profiles add column if not exists monthly_learning_hours numeric not null default 10;
alter table profiles add column if not exists weekly_content_target int not null default 3;
alter table profiles add column if not exists notifications_enabled boolean not null default true;
alter table profiles add column if not exists theme text not null default 'dark';
alter table tasks add column if not exists deadline date;
alter table tasks add column if not exists project_id uuid references projects(id) on delete set null;
alter table tasks add column if not exists parent_task_id uuid references tasks(id) on delete set null;
alter table tasks add column if not exists carry_count int not null default 0;
alter table tasks add column if not exists source text;
alter table leads add column if not exists industry text;
alter table leads add column if not exists contact_email text;
alter table leads add column if not exists contact_phone text;
alter table leads add column if not exists source text;
alter table leads add column if not exists relationship_strength int not null default 1;
alter table leads add column if not exists site text;
alter table daily_plans add column if not exists score int;
alter table daily_plans add column if not exists generated_at timestamptz;
create index if not exists tasks_user_status_due on tasks(user_id,status,due_at);
create index if not exists transactions_user_date on transactions(user_id,occurred_on);
create index if not exists leads_user_followup on leads(user_id,next_follow_up);
create index if not exists events_user_start on events(user_id,starts_at);
create index if not exists time_blocks_user_start on time_blocks(user_id,starts_at);
create index if not exists health_user_date on health_entries(user_id,entry_date);
create index if not exists journal_user_date on journal_entries(user_id,entry_date);
create index if not exists experiences_user_date on experiences(user_id,experience_date);
create index if not exists notifications_user_read on notifications(user_id,read_at);
alter table projects enable row level security; alter table time_blocks enable row level security; alter table content_items enable row level security; alter table sales_activities enable row level security; alter table health_entries enable row level security; alter table network_contacts enable row level security; alter table experiences enable row level security; alter table journal_entries enable row level security; alter table notifications enable row level security; alter table daily_scores enable row level security;
create policy projects_self on projects for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy time_blocks_self on time_blocks for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy content_self on content_items for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy sales_activities_self on sales_activities for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy health_self on health_entries for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy network_self on network_contacts for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy experiences_self on experiences for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy journal_self on journal_entries for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy notifications_self on notifications for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy daily_scores_self on daily_scores for all using(user_id=auth.uid()) with check(user_id=auth.uid());