alter table profiles add column if not exists day_type_overrides jsonb not null default '{}'::jsonb;
alter table tasks add column if not exists goal_id uuid references goals(id) on delete set null;
alter table tasks add column if not exists import_key text;
alter table goals add column if not exists progress numeric not null default 0;
alter table goals add column if not exists start_date date;
alter table goals add column if not exists end_date date;
alter table goals add column if not exists notes text;
alter table leads add column if not exists contact text;
alter table leads add column if not exists industry text;
alter table leads add column if not exists contact_email text;
alter table leads add column if not exists contact_phone text;
alter table leads add column if not exists source text;
alter table leads add column if not exists relationship_strength int not null default 1;
alter table leads add column if not exists site text;
alter table content_items add column if not exists import_key text;
alter table transactions add column if not exists import_key text;
alter table learning_modules add column if not exists project text;
alter table learning_modules add column if not exists notes text;
alter table learning_modules add column if not exists current_level text;
alter table learning_modules add column if not exists target_level text;
alter table health_entries add column if not exists import_key text;
alter table experiences add column if not exists import_key text;
alter table network_contacts add column if not exists import_key text;
alter table events add column if not exists import_key text;
create table if not exists learning_sessions(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,module_id uuid references learning_modules(id) on delete set null,session_date date not null,minutes int not null check(minutes>=0),notes text,applied_to_tdo text,project text,confidence_after int check(confidence_after between 0 and 100),created_at timestamptz not null default now());
create table if not exists founder_lab_entries(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,week_start date not null,theme text not null,concept text,lesson text,exercise text,challenge text,reflection text,created_at timestamptz not null default now(),unique(user_id,week_start));
create index if not exists tasks_user_import on tasks(user_id,import_key);
create index if not exists content_user_import on content_items(user_id,import_key);
create index if not exists transactions_user_import on transactions(user_id,import_key);
create index if not exists learning_sessions_user_date on learning_sessions(user_id,session_date);
alter table learning_sessions enable row level security;
alter table founder_lab_entries enable row level security;
drop policy if exists learning_sessions_self on learning_sessions;
drop policy if exists founder_lab_self on founder_lab_entries;
create policy learning_sessions_self on learning_sessions for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy founder_lab_self on founder_lab_entries for all using(user_id=auth.uid()) with check(user_id=auth.uid());